const translations = {
    ru: {
        subtitle: "Первый в мире по-настоящему универсальный дистрибутив Linux v1.0",
        desc: "Релиз 1.0 от ООО «Болваос». Один дистрибутив Linux From Scratch для всего: от ThinkPad 1999 года до Steam Deck, PlayStation 5, телевизоров LG, БЕЛАЗов и касс.",
        selectDevice: "🎯 Выбери своё устройство:",
        noviceBtn: "👶 Для новичков (GUI)",
        terpilaBtn: "💀 Для терпил (TTY / Gentoo-Style)",
        mellstroyBait: "🚀 ООО «Болваос» — мы не просто делаем Linux From Scratch. Мы переворачиваем индустрию. Скоро во всех ИТ-челленджах планеты.",
        instructionBtn: "📖 Инструкция по установке рядом с Windows",
        playerTitle: "📺 Медиаплеер Bolval (на движке libVLC)",
        featuresTitle: "🤖 Нативная поддержка APK",
        featuresDesc: "Благодаря встроенному контейнеру Waydroid, Bolval OS на телевизорах LG позволяет запускать любые Android-приложения!",
        fsTitle: "🗄️ Собственная файловая система: BurmaldaFS (Atomic Read-Only с ультра-сжатием ZSTD)",
        fsDesc: "Забудьте про Ext4 и NTFS! Собственная файловая система Burmalda от ООО «Болваос» защищает диски от поломок при сбоях питания и ускоряет чтение данных на SSD в 2.5 раза.",
        pricingTitle: "💼 Коммерческая поддержка и лицензирование от ООО «Болваос»",
        pricingSubtitle: "Готовые решения для автоматизации вашей ИТ-инфраструктуры",
        tier1Name: "🥐 Bolval Retail Lite",
        tier1Price: "990 ₽ <span>/ мес.</span>",
        tier1Desc: "Для пекарен, кафе и небольших магазинов. Включает прошивку под сенсорные моноблоки, интеграцию с кассами АТОЛ и интерфейс с большими кнопками.",
        badgePopular: "Популярно",
        tier2Name: "🏢 Enterprise Infrastructure",
        tier2Price: "4 900 ₽ <span>/ устройство</span>",
        tier2Desc: "Для школ, больниц и крупных торговых сетей. Удаленное управление классом Veyon, шифрование ГОСТ, поддержка DICOM-снимков и кастомный пакетный менеджер XBX с поддержкой ручной компиляции из исходников по флагам -O3.",
        tier3Name: "🏦 FinTech Core",
        tier3Price: "По запросу",
        tier3Desc: "Для банкоматов Сбера, Т-Банка и биометрических терминалов Kozen P12. Сертификация PCI DSS, интеграция со слоем InterSphere и защита Secure MCU.",
        partnersTitle: "🤝 Технологическое содружество",
        partnersSubtitle: "Bolval OS 1.0 развивается содружеством ООО «Болваос» и ведущих ИТ-компаний",
        partnerYandex: "Интеграция Яндекс Браузера, голосового ассистента Алиса и высокоскоростных репозиториев XBX в Yandex Cloud.",
        partnerVK: "Встроенный магазин приложений RuStore, интеграция медиа-сервисов VK и оптимизация для мобильных устройств.",
        partnerKaspersky: "Защита ядра Linux CachyOS модулями Kaspersky SDK. Безопасность финансовых транзакций в банкоматах и ритейле.",
        partnerNvidia: "Встроенная поддержка проприетарных драйверов NVIDIA, автоматическое переключение графических слоев и оптимизация Vulkan/Mesa для максимального FPS в играх через Steam.",
        partnerValve: "Полная интеграция с игровым слоем Valve Proton и композитором Gamescope. Максимальная производительность Steam Deck и автозапуск Steam Big Picture в один клик.",
        partnerUbisoft: "🕹️ Оптимизация игровых движков Ubisoft Anvil и Snowdrop под ядро Linux CachyOS. Максимальный FPS и стабильность графики Radeon RX в AAA-играх.",
        starBtn: "⭐ Star on GitHub",
        modalTitle: "🛠️ Руководство по Dual-Boot: Windows + Bolval OS",
        step1Title: "1. Выделение места в Windows:",
        step1Desc: "Нажми правой кнопкой на пуск в Windows, выбери «Управление дисками». Кликни правой кнопкой на диск C:, выбери «Сжать том» и освободи минимум 30–50 ГБ неразмеченного места для Bolval OS Shell.",
        step2Title: "2. Запись образа:",
        step2Desc: "Скачай утилиту Rufus на Windows. Вставь флешку, выбери скачанный iso-образ Bolval OS и запиши его в режиме GPT/UEFI.",
        step3Title: "3. Настройка БИОС (UEFI):",
        step3Desc: "Перезагрузи ПК, зайди в BIOS (обычно клавиша F2, F12 или Del). Обязательно отключи функцию Secure Boot, иначе кастомное ядро CachyOS с планировщиком BORE заблокируется системой защиты Windows.",
        step4Title: "4. Установка через Calamares:",
        step4Desc: "Загрузись с флешки в режиме «Для новичков». Запустится графика в стиле COSMIC. В установщике Calamares выбери пункт «Установить рядом с Windows» и укажи то свободное место, которое мы очистили на первом шаге.",
        step5Title: "5. Финальный выбор:",
        step5Desc: "После перезагрузки тебя встретит наше красивое меню GRUB с логотипом Bolval OS, где ты сможешь выбрать: загрузить Windows для обычных задач или запустить Bolval OS в режиме графики или TTY!",
        footerLocation: "🚀 Будущая штаб-квартира: Dubai Internet City (ОАЭ) — ООО «Болваос» (Bolvaos Tech)."
    },
    en: {
        subtitle: "The World's First Truly Universal Linux Distribution v1.0",
        desc: "Release 1.0 by LLC Bolvaos. A single Linux From Scratch distribution for everything: from 1999 ThinkPads to Steam Deck, PlayStation 5, LG Smart TVs, and industrial infrastructure.",
        selectDevice: "🎯 Select your device:",
        noviceBtn: "👶 For Beginners (GUI)",
        terpilaBtn: "💀 For Hardcore Users (TTY / Gentoo-Style)",
        mellstroyBait: "🚀 LLC Bolvaos — we don't just build Linux From Scratch. We rewrite the rules of the industry. Coming soon to every tech challenge on Earth.",
        instructionBtn: "📖 Dual-Boot Windows Installation Guide",
        playerTitle: "📺 Bolval Media Player (powered by libVLC)",
        featuresTitle: "🤖 Native APK Support",
        featuresDesc: "Thanks to the built-in Waydroid container, Bolval OS on LG TVs allows you to run any Android applications natively!",
        fsTitle: "🗄️ Proprietary File System: BurmaldaFS (Atomic Read-Only with ultra ZSTD compression)",
        fsDesc: "Forget Ext4 and NTFS! The proprietary Burmalda file system by LLC Bolvaos protects drives from corruption during power failures and accelerates SSD read speeds by 2.5x.",
        pricingTitle: "💼 Commercial Support & Licensing by LLC Bolvaos",
        pricingSubtitle: "Turnkey solutions for automating your IT infrastructure",
        tier1Name: "🥐 Bolval Retail Lite",
        tier1Price: "$15 <span>/ mo.</span>",
        tier1Desc: "For bakeries, cafes, and small shops. Includes touchscreen firmware, ATOL POS integration, and large-button UI layouts.",
        badgePopular: "Popular",
        tier2Name: "🏢 Enterprise Infrastructure",
        tier2Price: "$65 <span>/ device</span>",
        tier2Desc: "For schools, hospitals, and major retail networks. Veyon remote management, GOST cryptography, DICOM imaging, and custom XBX Package Manager with native source compilation flags (-O3 enabled).",
        tier3Name: "🏦 FinTech Core",
        tier3Price: "On Request",
        tier3Desc: "For Sberbank/T-Bank ATMs and Kozen P12 biometric terminals. PCI DSS compliance, InterSphere middleware abstraction, and Secure MCU encryption.",
        partnersTitle: "🤝 Strategic Technology Alliance",
        partnersSubtitle: "Bolval OS 1.0 is developed in collaboration with LLC Bolvaos and leading IT corporations",
        partnerYandex: "Integration of Yandex Browser, Alice voice assistant, and high-speed XBX repositories powered by Yandex Cloud.",
        partnerVK: "Built-in RuStore application marketplace, native VK media ecosystem integration, and mobile platform optimizations.",
        partnerKaspersky: "Linux CachyOS kernel hardening via Kaspersky SDK modules. Enterprise-grade security for retail and ATM networks.",
        partnerNvidia: "Out-of-the-box NVIDIA proprietary driver integration, automatic hardware layer switching, and Vulkan optimizations for maximum gaming FPS via Steam.",
        partnerValve: "Full integration with Valve Proton compatibility layer and Gamescope compositor. Out-of-the-box Steam Deck optimization with one-click Steam Big Picture autostart.",
        partnerUbisoft: "🕹️ Optimization of Ubisoft Anvil and Snowdrop engines for the Linux CachyOS core. Maximum FPS and Radeon RX graphics stability in AAA gaming.",
        starBtn: "⭐ Star on GitHub",
        modalTitle: "🛠️ Dual-Boot Guide: Windows + Bolval OS",
        step1Title: "1. Allocate Space in Windows:",
        step1Desc: "Right-click the Windows Start menu, select 'Disk Management'. Right-click Drive C:, select 'Shrink Volume', and free up at least 30-50 GB of unallocated space for Bolval OS Shell.",
        step2Title: "2. Flash the Image:",
        step2Desc: "Download Rufus on Windows. Insert your USB drive, select the downloaded Bolval OS ISO, and flash it using GPT/UEFI mode.",
        step3Title: "3. Configure BIOS (UEFI):",
        step3Desc: "Reboot your PC, enter BIOS (usually F2, F12, or Del). Ensure Secure Boot is Disabled, otherwise the custom CachyOS kernel with the BORE scheduler will be blocked by Windows security layers.",
        step4Title: "4. Installation via Calamares:",
        step4Desc: "Boot from the USB in 'Beginners Mode'. The COSMIC-inspired GUI will launch. In the Calamares installer, select 'Install alongside Windows' and target the unallocated space from step 1.",
        step5Title: "5. The Final Choice:",
        step5Desc: "After rebooting, you will be greeted by our custom GRUB boot menu with the Bolval OS logo, allowing you to choose between booting Windows or launching Bolval OS in GUI or TTY mode!",
        footerLocation: "🚀 Future HQ: Dubai Internet City (UAE) — LLC Bolvaos (Bolvaos Tech)."
    }
};

